### ISSUE TITLE
Smart meter modbus addresses

### ISSUE THREAD

**Issue by dst10** [That-Dude/Emulated-Eastrom-SDM-Power-Meter#4]
Hi,
Really nice contribution! I'm dealing with a similar project right now, but in my case I can use an Eastrom smart meter. I would like to ask you which are the modbus addresses Growatt inverter uses for read smart meter data. I'm trying to read inverter and smart meter data via Modbus RTU connecting esp32 to inverter communication port. I have no problem retrieving inverter data but I can't find the way to retrieve smart meter data.
Thank you in advence!

**Comment by That-Dude** [comment]
Hi dst10, just to clarify, are you saying that you have an Eastron and you want to read data from it but don't know what the modbus addresses on the meter?

I have a PDF in this repo with all of the Eastron addresses in it, but there are lots of other projects that already do this, you can just borrow their code.

**Comment by dst10** [comment]
Hi,
I understand that these are the addresses on the meter but as the meter is connected to the inverter (and with the same modbus id 001) I'm not sure if an esp32 connected to the inverter could read smart meter data using the addresses on the PDF you mention or now they are somewhere else (because of confusion between inverter and meter). Hope I explain the issue well :) Thank you!

**Comment by That-Dude** [comment]
Most Growatt Inverters have two modbus interfaces, one is used to control the inverter and the one is connected to the Eastron meter. You need to connect your device onto the bus with the meter to read it's settings. Does that make sense?

**Comment by dst10** [comment]
Thats makes perfect sense. I think the problem I have is that inverter and meter has the same id. I can read inverter data without any problem. But when I try to read smart meter modbus register 6 for example, as it has the same id as inverter, it retrieves value of the modbus register 6 but of the inverter. I know the problem is that they are in the same bus, but when I change smart meter id, a warning appears. I googled it and it is necessary that inverter and meter have the same id. It's driving me crazy.
Thank you

**Comment by That-Dude** [comment]
I think that's you're getting confused. If you are reading the inverter data then you must be on modbus-A. The meter is on mobus-B and it doesn't matter that it has the same ID as the inverter on Modbus-A as it's a completely different bus (interface).

**Comment by dst10** [comment]
Sorry, just starting in the modbus world...When I send signal to read/write I just need to know slave_id, starting_address and registers_quantity. If I'm trying to access data from two different devices using the same physical communication port and they have the same slave_id, I don't know how to differenciate. I understand your point of different bus. But how I tell esp32 which bus to communicate with?
![portpins](https://user-images.githubusercontent.com/127786365/225590330-f66bf02a-d285-4a93-8b4c-4f5febe7c3c3.png)
ith?
I attach my connections.
Thank you for your time and your fast answers.

**Comment by That-Dude** [comment]
Ok so ignoring your project your growatt invert is working fine with the Eastron meter right? If that's the case, your ESP32 will need a separate modbus interface connected to the bus on pins 7 and 8 in the image above. On that bus the easton is the mater with ID 1 (or whatever) and the growatt inverter is a slave device with an ID of 2 (or whatever). You're esp32 interface that is connected to that bus just needs to set it's slave ID to something other than the ones currently in use.

I might be wrong, but it sounds like your esp32 is currently connected to the bus on pins 3/4 so that you can read the inverter stats. The ESP needs two seperate interfaces, one on each bus.

**Comment by dst10** [comment]
Fully understood now. Yes, my growatt inverter is working fine with the smart meter. Just trying to develop by my own a monitoring device for inverter and smart meter data. I was trying to read both inverter and smart meter data from pins 3/4...I will implement these two separate interfaces
Thanks for the help!
